# Generated by Django 3.1.2 on 2020-10-28 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('crops', models.TextField()),
                ('userType', models.TextField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('lastActiveOn', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
